### ISSUE TITLE
New Update broke Skip Intro Button and also not completely a fan of moving every Button to the middle

### ISSUE THREAD

**Issue by Mr3DAlien** [tedhinklater/finimalism#13]
![Screenshot 2024-11-09 172341](https://github.com/user-attachments/assets/b52ab00b-bf47-44d4-abc6-e7ff06932ade)

The newest update broke the new skip intro button. It worked before, but now it won't anymore. Already tried without the theme and then it worked again.

I am also not really a fan of moving every button in the middle of the screen. If it was up to me I wouldn't even like the play button in the middle. Please make it optional for people to choose which they prefer. I guess that this change also somehow made the skip intro button no longer work.

**Comment by tedhinklater** [comment]
Ok the repositioned buttons are put back. The Skip Intro button should be working, are you using JMP? It has to be enabled in Client Settings. Either way, the new/restored css is up, sorry about that

**Comment by Mr3DAlien** [comment]
Sorry I what exactly do you mean with JMP? I did have Ask to Skip enabled for everything. As soon as I did disable the theme the skip intro button reapears in videos. It seems to still not work for me. Your theme enabled removes it and your theme disabled enables it again. It did work before.

Also huge thanks for changing the buttons back :D

**Comment by tedhinklater** [comment]
hmmm ok I'll remove all the intro-skip stuff for now and try again, 10.10.x seems to have done more than I thought. Thanks for the info

**Comment by Mr3DAlien** [comment]
Ahh I understand. I use Jellyfin Web, but it still does not seem to work. I tried it on 3 different systems deleted the cache and everything, but it still only works with your theme disabled

**Comment by tedhinklater** [comment]
Bizarre, let's check we're doing the same thing. Do you have intro-skipper plugin 1.10.10.7 installed and active? 

If I disable my css, I get two skip intro buttons, one white and one blue. 
I think the blue one is the intro-skipper plugin (1.10.10.7, css is **#skipIntro .emby-button**) and the white one is something new in JF 10.10 (CSS is **.skip-button**)

I added **.skip-button { display: none;}** to hide the new white one, and only some code to change the colour of the plugin one.

**Comment by Mr3DAlien** [comment]
I run on Jellyfin 10.10.1 and have intro-skipper 10.10.6. I have the intro skipper plugin skip button disabled and set everything iny my web client to ask to skip. When enabling the custom CSS I can't see the skip button, but if I disable the CSS the skip button appears (white with rounded corners). I guess here is the problem, since you use the plugin one and removed the default one, where I want to use the default one and not the plugin one.

**Comment by Mr3DAlien** [comment]
Is there a reason I should use the plugin one over the default one? Because I would prefer the official one as it should work on more clients in the future like the firetv stick. I don't really understood why the skip plugin adds its own

**Comment by tedhinklater** [comment]
That makes sense, I've restored the white (official) one now. I'll also disable the plugin one if it's what everyone else will probably do. Thanks for the info :)

If you want to just add a line quickly to the bottom of your css box to add the fix it's

`.skip-button { display: block; }`


Thanks again

**Comment by tedhinklater** [comment]
the "block" fix looks a bit weird but the github one is normal, hopefully it updates soon
![fix](https://github.com/user-attachments/assets/b58af565-c1ca-4a82-8786-db2882c0eb47)

**Comment by tedhinklater** [comment]
It's updated
